import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '@/app/css/global.css'
import '@/app/css/reset.css'
import '@/app/css/theme.css'
import '@/app/css/typo.css'
import '@/app/css/util.css'

import Header from './components/Header'
import Footer from './components/Footer'

const font = Inter({
  variable: '--font',
  weight: '300',
  subsets: ['cyrillic', 'latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className={`${font.variable}`} lang="en">
      <body className={`${font.className}`}>
        <Header/>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
